#!/bin/sh
alias j='z'
alias f='zi'
alias sz='source $HOME/.zshrc'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

# custom stuff
alias v='nvim'
alias ccht='curl cht.sh'
alias cht='cht.sh'
alias down='downgrade'
alias ls='exa -al --color=always --group-directories-first'
# alias ls='ls_extended -A -s'
alias usb='sudo mount --uuid AB2D-8744 /run/media/brian'
alias green='rgb_keyboard -l fixed -c 04ff04'
alias multi='rgb_keyboard -l swirl -c multi'
alias mp='mdpdf'
alias dc='clipdel -d'
alias dca='clipdel -d .'
alias lf='lfrun'

# Git aliases
alias gcm='git checkout origin master'
alias gpsh='git push origin HEAD'
alias gpom='git pull origin master'
alias gpod='git pull origin develop'

# Python
alias python='python3'

# dotfiles
alias config='/usr/bin/git --git-dir=/home/ellice/dots/ --work-tree=/home/ellice'
