#! /bin/sh
# kill programs
killall -q picom
killall -q sxhkd
killall -q polybar

while pfrep -u $UID -x picom >/dev/null; do sleep 1; done
while pfrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pfrep -u $UID -x polybar >/dev/null; do sleep 1; done

# autostart apps
picom & 
sxhkd &

#if [[ $(xrandr -q | grep 'Virtual2 connected')]]; then
	#xrandr --output Virtual1 --primary --mode 1920x1080 --rotate normal --output Virtual2 --mode 1920x1080 --rotate normal --left-of Virtual1
#fi

~/.config/polybar/launch.sh

#pgrep -x sxhkd > /dev/null || sxhkd &
#$HOME/.config/polybar/launch.sh

# colors
FOCUSED_BORDER_COLOR="#5b1d4a"
NORMAL_BORDER_COLOR="#5b5558"
ACTIVE_BORDER_COLOR="#262734"
PRESEL_FEEDBACK_COLOR="#D6A36A"

#bspc monitor Virtual1 -d 1 2 3 4 5
#bspc monitor Virtual2 -d 6 7 8 9 10 
bspc monitor Virtual1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           6
bspc config top_padding          45
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config normal_border_color   "$NORMAL_BORDER_COLOR"
bspc config active_border_color   "$ACTIVE_BORDER_COLOR"
bspc config focused_border_color  "$FOCUSED_BORDER_COLOR"
bspc config presel_feedback_color "$PRESEL_FEEDBACK_COLOR"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura  desktop='^5' state=tiled

feh --bg-fill $HOME/Pictures/wallpapers/wallpaper7.jpg
xsetroot -cursor_name left_ptr &

